### ISSUE TITLE
Blog post has a 404 link.

### ISSUE THREAD

**Issue by vpakg** [spatie/murze.be#17]
@freekmurze Thanks as always for your collaborations.

Apologies, this is not directly related to the project co code-base itself, but I couldn't find another place to report. 

On the [blog post ﻿about this project](https://murze.be/on-migrating-my-blog-from-wordpress-to-a-laravel-application) the paragraph "**Behind the scenes**"  has a link which takes the user to a 404 page https://spatie.be/en/spatie/murze.be

Thanks!

**Comment by freekmurze** [comment]
Fixed, thanks for letting me know!
