### ISSUE TITLE
No sitemap.xml on merze.be

### ISSUE THREAD

**Issue by Jaro13** [spatie/murze.be#28]
Thanks for the article: https://murze.be/automatically-generate-a-sitemap-in-laravel. I've noticed You didn't implement sitemap.xml on your website.  Is this true? Any plans for implementation? It's always a good idea to walk your talk. Thank You anyway!

**Comment by freekmurze** [comment]
I'm walking my talk. 😄 

From my blog article:

> But for small to medium-sized sites where all url's are linked properly, I'd conclude, when reading Google's documentation, that a sitemap is not needed per se.
