### ISSUE TITLE
YouTube video's aren't displayed correctly on mobile

### ISSUE THREAD

**Issue by freekmurze** [spatie/murze.be#31]
As [reported](https://twitter.com/alexisferat/status/963676656253788160) on Twitter, YouTube video's aren't displayed correctly on mobile. 

Example url: https://murze.be/inside-the-browsers-event-loop

**Comment by rowdyrabouw** [comment]
iframe {
 max-width: 100%;
}

should do the trick :-)

**Comment by freekmurze** [comment]
Thanks for the tip!
