### ISSUE TITLE
postSeeder can create only one post, the second one will get error

### ISSUE THREAD

**Issue by wwp66650** [spatie/murze.be#42]
`art db:seed --class=PostSeeder`

 `Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value (SQL: insert into `posts` (`title`, `text`, `publish_date`, `published`, `original_content`, `updated_at`, `created_at`) values (Pariatur et praesentium in molestias dolorem., Itaque asperiores molestiae quia est amet maiores reiciendis. Molestiae labore qui nam commodi a. Ratione autem sint cumque ea et cupiditate dolorem. Voluptatem explicabo corporis totam quia quidem laborum ea., 2014-03-06 20:58:32, 1, 0, 2018-08-26 02:54:32, 2018-08-26 02:54:32))`

**Comment by freekmurze** [comment]
This is now fixed in the master branch.
