### ISSUE TITLE
Trying to get my own instance going with valet, nova license and get a github error

### ISSUE THREAD

**Issue by csajedi** [spatie/murze.be#45]
So I am trying to follow along with your website to get my own online, I've gone through these steps to serve it locally:

1. clone the repo
2. Start a new project with `composer global require "laravel/installer"` then `laravel new site`
3. cp -R all of the murz.be files to my new site `cp -R ../murz.be .`
4. overwrite: "repositories" in composer.json
```json
{
        "type": "composer",
        "url": "https://nova.laravel.com"
  }
```
5. overwrite "require" in composer.json:
```json
"laravel/nova": "*",
```
4. I ran `composer clear-cache` then `composer update` but I already copied my github token before I realized I needed to purchase nova, so I did. But now when I run `composer update` I get:
```
[Composer\Downloader\TransportException]                
  The "https://api.github.com/repos/laravel/nova" file c  
  ould not be downloaded (HTTP/1.1 404 Not Found)  

```

Any ideas why I could be getting this error?

**Comment by freekmurze** [comment]
You're probably doing something wrong with installing Nova. Here are the official instructions: https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer

**Comment by csajedi** [comment]
I have also tried simply cloning the repo and `valet link` the directory and I get:

> Warning: require(/Users/Professional/code/murze.be/public/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/Professional/code/murze.be/public/index.php on line 24

>Fatal error: require(): Failed opening required '/Users/Professional/code/murze.be/public/../vendor/autoload.php' >(include_path='.:/usr/local/Cellar/php@7.1/7.1.22/share/php@7.1/pear') in /Users/Professional/code/murze.be/public/index.php on line 24


Is there a common set of steps to get the repo working locally? I am not new to Laravel, but the rest of the toolchain, including valet is new to me.

**Comment by csajedi** [comment]
> You're probably doing something wrong with installing Nova. Here are the official instructions: https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer

I have posted my steps following that documentation. I get stuck at:

>After your composer.json file has been updated, run the composer update command in your console terminal:

>composer update

Maybe someone else using the repo has already surmounted this problem?

**Comment by zeshan77** [comment]
I face the same issue. Did you find a solution @csajedi ?
