### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by markotitel** [spatie/murze.be#48]
Hi,

I am learning Laravel and was watching a video on you dashboard.  Then found your blog is open source, and has everything I need to read in order to learn how to properly use design patterns and Laravel.
My level is write all in controllers = ).

Came to the point of integrating Stripe into small web app I am making.

Just wanted to confirm so I do not mislead myself.
You intentionally did not finished payments or am I missing something?

Regards and thanks for the two examples (Dashboard and murze) from which everyone can learn.

**Comment by freekmurze** [comment]
The payments functionality is finished and working fine. You can send me
money here :-) https://murze.be/payments




Freek Van der Herten
https://spatie.be

**Comment by markotitel** [comment]
Hi, thanks for quick reply.

I cannot send you money. It redirects back. Like validator is not validating and redirecting back to the payments page. I do not get to Stripe checkout.

**Comment by freekmurze** [comment]
Seems to work perfectly here

![image](https://user-images.githubusercontent.com/483853/47646560-95294800-db74-11e8-858c-2233decf61ac.png)
